begin;
truncate table public.event_speakers, public.gallery_items, public.events, public.tracks, public.speakers, public.societies, public.sponsors, public.team_members, public.faqs, public.testimonials, public.site_blocks restart identity cascade;
insert into public.site_blocks (key, data) values ('settings', '{"name":"st(AI)rway","tagline":"Climb into the future of AI, one weekend at a time.","supportLine":"A weekend AI event series by IEEE SB College of Engineering Kidangoor.","altTaglines":["Every weekend, one step higher.","From zero to AI builder.","Your next step is waiting.","The stairway doesn''t climb itself."],"description":"Climb into the future of AI, one weekend at a time. Workshops, talks, labs and a hackathon by IEEE Student Branch, College of Engineering Kidangoor.","siteUrl":"https://stairway.pages.dev","organizer":{"name":"IEEE Student Branch, College of Engineering Kidangoor","short":"IEEE SB CEK","url":"https://ieeesbcek.org"},"venue":{"name":"College of Engineering Kidangoor","hall":"Main Seminar Hall, Block A","address":"Kidangoor South P.O., Kottayam, Kerala 686583, India","city":"Kottayam","region":"Kerala","country":"IN","postalCode":"686583","mapEmbed":"https://www.google.com/maps?q=College+of+Engineering+Kidangoor&output=embed","mapLink":"https://maps.google.com/?q=College+of+Engineering+Kidangoor"},"registration":{"mode":"onsite","googleFormUrl":"https://forms.gle/your-form-id","endpoint":""},"newsletter":{"endpoint":""},"gaId":"","announcement":{"enabled":true,"text":"Registrations open for Step {step}: {title} — limited seats!"},"aftermovieUrl":"https://www.youtube.com/embed/dQw4w9WgXcQ","sponsorDeckUrl":"","speakerFormUrl":"https://forms.gle/speak-at-stairway","volunteerFormUrl":"https://forms.gle/volunteer-stairway","contact":{"email":"stairway@ieeesbcek.org","sponsorEmail":"sponsors@ieeesbcek.org","coordinators":[{"name":"Aditya Menon","role":"Event Coordinator","phone":"+91 94470 12345"},{"name":"Fathima Rasheed","role":"Event Coordinator","phone":"+91 96330 67890"}]},"social":{"instagram":"https://instagram.com/ieeesbcek","linkedin":"https://linkedin.com/company/ieee-sb-cek","whatsapp":"https://chat.whatsapp.com/your-community-invite","youtube":"https://youtube.com/@ieeesbcek","github":"https://github.com/ieeesbcek"},"ieee":{"joinUrl":"https://www.ieee.org/membership/join/index.html","branchUrl":"https://ieeesbcek.org"}}'::jsonb), ('stats', '{"items":[{"label":"Weekends","value":12,"suffix":""},{"label":"Sessions","value":30,"suffix":"+"},{"label":"Participants","value":500,"suffix":"+"},{"label":"Speakers","value":20,"suffix":"+"},{"label":"Projects built","value":80,"suffix":"+"}]}'::jsonb);
insert into public.societies (slug, name, short_name, description, color, sort_order) values ('main', 'IEEE Student Branch CEK', 'Main IEEE', 'The branch-wide stairway: research, security, data and generative media.', 'yellow', 0);
insert into public.tracks (society_id, name, sort_order) select s.id, 'AI × Research & Innovation', 0 from public.societies s where s.slug = 'main';
insert into public.tracks (society_id, name, sort_order) select s.id, 'AI × Cybersecurity', 1 from public.societies s where s.slug = 'main';
insert into public.tracks (society_id, name, sort_order) select s.id, 'AI × Data Analytics', 2 from public.societies s where s.slug = 'main';
insert into public.tracks (society_id, name, sort_order) select s.id, 'AI × Generative Media', 3 from public.societies s where s.slug = 'main';
insert into public.societies (slug, name, short_name, description, color, sort_order) values ('cs', 'IEEE Computer Society', 'CS', 'Build software with AI: web, apps, cloud and engineering practice.', 'blue', 1);
insert into public.tracks (society_id, name, sort_order) select s.id, 'AI × Web Development', 0 from public.societies s where s.slug = 'cs';
insert into public.tracks (society_id, name, sort_order) select s.id, 'AI × App Development', 1 from public.societies s where s.slug = 'cs';
insert into public.tracks (society_id, name, sort_order) select s.id, 'AI × Cloud & DevOps', 2 from public.societies s where s.slug = 'cs';
insert into public.tracks (society_id, name, sort_order) select s.id, 'AI × Software Engineering', 3 from public.societies s where s.slug = 'cs';
insert into public.societies (slug, name, short_name, description, color, sort_order) values ('ias', 'IEEE Industry Applications Society', 'IAS', 'AI on the factory floor: automation, maintenance, twins and manufacturing.', 'orange', 2);
insert into public.tracks (society_id, name, sort_order) select s.id, 'AI × Industrial Automation', 0 from public.societies s where s.slug = 'ias';
insert into public.tracks (society_id, name, sort_order) select s.id, 'AI × Predictive Maintenance', 1 from public.societies s where s.slug = 'ias';
insert into public.tracks (society_id, name, sort_order) select s.id, 'AI × Digital Twins', 2 from public.societies s where s.slug = 'ias';
insert into public.tracks (society_id, name, sort_order) select s.id, 'AI × Smart Manufacturing', 3 from public.societies s where s.slug = 'ias';
insert into public.societies (slug, name, short_name, description, color, sort_order) values ('ras', 'IEEE Robotics & Automation Society', 'RAS', 'Machines that see and move: robotics, vision, autonomy and ROS.', 'green', 3);
insert into public.tracks (society_id, name, sort_order) select s.id, 'AI × Robotics', 0 from public.societies s where s.slug = 'ras';
insert into public.tracks (society_id, name, sort_order) select s.id, 'AI × Computer Vision', 1 from public.societies s where s.slug = 'ras';
insert into public.tracks (society_id, name, sort_order) select s.id, 'AI × Autonomous Systems', 2 from public.societies s where s.slug = 'ras';
insert into public.tracks (society_id, name, sort_order) select s.id, 'AI × ROS', 3 from public.societies s where s.slug = 'ras';
insert into public.societies (slug, name, short_name, description, color, sort_order) values ('wie', 'IEEE Women in Engineering', 'WIE', 'Women building AI for everyone — health, inclusion, impact and leadership.', 'purple', 4);
insert into public.tracks (society_id, name, sort_order) select s.id, 'AI × HealthTech', 0 from public.societies s where s.slug = 'wie';
insert into public.tracks (society_id, name, sort_order) select s.id, 'AI × Inclusive Design', 1 from public.societies s where s.slug = 'wie';
insert into public.tracks (society_id, name, sort_order) select s.id, 'AI × Social Impact', 2 from public.societies s where s.slug = 'wie';
insert into public.tracks (society_id, name, sort_order) select s.id, 'AI × Entrepreneurship & Leadership', 3 from public.societies s where s.slug = 'wie';
insert into public.speakers (slug, name, designation, organization, photo_url, bio, topic, links, sort_order) values ('anjali-nair', 'Anjali Nair', 'Senior ML Engineer', 'Nimbus Labs, Bengaluru', null, 'Anjali builds language models for Indic languages and has shipped NLP systems used by millions. A CEK alumna, she started her AI journey in this very seminar hall.', 'Foundations & NLP', '{"linkedin":"https://linkedin.com","x":"https://x.com"}'::jsonb, 0);
insert into public.speakers (slug, name, designation, organization, photo_url, bio, topic, links, sort_order) values ('rahul-varghese', 'Rahul Varghese', 'Data Scientist', 'Backwater Analytics, Kochi', null, 'Rahul turns messy public datasets into decisions for state agencies. He teaches Pandas like it''s a detective story.', 'Python for AI', '{"linkedin":"https://linkedin.com","website":"https://example.com"}'::jsonb, 1);
insert into public.speakers (slug, name, designation, organization, photo_url, bio, topic, links, sort_order) values ('meera-krishnan', 'Dr. Meera Krishnan', 'Assistant Professor, CSE', 'College of Engineering Kidangoor', null, 'Meera researches interpretable machine learning and fairness in healthcare models. She has supervised 20+ student ML projects.', 'Machine Learning', '{"linkedin":"https://linkedin.com"}'::jsonb, 2);
insert into public.speakers (slug, name, designation, organization, photo_url, bio, topic, links, sort_order) values ('arjun-pillai', 'Arjun Pillai', 'Embedded AI Engineer', 'Edgeworks Robotics, Technopark', null, 'Arjun puts neural networks on microcontrollers for agricultural drones. He believes every model should fit on a ₹500 board.', 'Computer Vision & Edge AI', '{"linkedin":"https://linkedin.com","x":"https://x.com"}'::jsonb, 3);
insert into public.speakers (slug, name, designation, organization, photo_url, bio, topic, links, sort_order) values ('sneha-thomas', 'Sneha Thomas', 'Computer Vision Researcher', 'IIIT Kottayam', null, 'Sneha works on generative models for medical imaging and runs a weekend art collective that paints with diffusion models.', 'Vision & Generative AI', '{"linkedin":"https://linkedin.com","website":"https://example.com"}'::jsonb, 4);
insert into public.speakers (slug, name, designation, organization, photo_url, bio, topic, links, sort_order) values ('vishnu-prasad', 'Vishnu Prasad', 'Deep Learning Engineer', 'Monsoon AI, Kochi', null, 'Vishnu trains large models for a living and debugs exploding gradients for fun. Kaggle Master, PyTorch contributor.', 'Deep Learning & LLMs', '{"linkedin":"https://linkedin.com","x":"https://x.com"}'::jsonb, 5);
insert into public.speakers (slug, name, designation, organization, photo_url, bio, topic, links, sort_order) values ('dr-joseph-mathew', 'Dr. Joseph Mathew', 'Principal Scientist, AI Safety', 'Indus Research Institute', null, 'Joseph leads evaluation research on large language models and advises policy bodies on responsible AI deployment.', 'LLMs & Responsible AI', '{"linkedin":"https://linkedin.com","website":"https://example.com"}'::jsonb, 6);
insert into public.speakers (slug, name, designation, organization, photo_url, bio, topic, links, sort_order) values ('nikhil-raj', 'Nikhil Raj', 'Founder & CTO', 'AgentForge', null, 'Nikhil''s startup builds AI agents for small businesses across Kerala. He has judged 15+ hackathons and still loves the 3 a.m. energy.', 'Agents & Prompt Engineering', '{"linkedin":"https://linkedin.com","x":"https://x.com","website":"https://example.com"}'::jsonb, 7);
insert into public.events (society_id, track_id, step_number, slug, title, topic, summary, description, starts_at, ends_at, venue, level, formats, agenda, outcomes, prerequisites, bring, capacity, price_paise, ticket_type, token_prefix, status, is_finale, resources, winners)
select s.id, t.id, 1, 'ai-unlocked', 'AI Unlocked', 'Foundations of Artificial Intelligence', 'What AI really is, what it isn''t, and the map of the field you''re about to climb.', 'The first step clears the fog. We separate AI from the hype, trace how search, learning and reasoning fit together, and build an intuition for how a machine turns data into decisions. You''ll leave with a mental map of the whole stairway and your first tiny model running in the browser.', '2026-08-29T09:30:00+05:30', '2026-08-29T16:30:00+05:30', 'Main Seminar Hall, Block A', 'Beginner', array['Talk','Workshop']::text[], '[{"time":"09:30","title":"Check-in & coffee","detail":"Grab your badge, find a seat, connect to Wi-Fi."},{"time":"10:00","title":"Keynote: The AI landscape in 2026"},{"time":"11:30","title":"Short break"},{"time":"11:45","title":"Guided walkthrough","detail":"Live coding with the speaker — follow along on your laptop."},{"time":"13:00","title":"Lunch"},{"time":"14:00","title":"Build-your-first-model challenge","detail":"Work in pairs. Mentors float between tables."},{"time":"16:00","title":"Show & tell","detail":"Three teams demo what they built."},{"time":"16:30","title":"Wrap-up & next step preview"}]'::jsonb, array['Explain the difference between AI, ML and deep learning without buzzwords','Describe how a model learns from examples','Train a simple image classifier with Teachable Machine','Plan your personal route through the series']::text[], array['None. Really — just show up.']::text[], array['Laptop or phone','Charger','A notebook for the big-picture map']::text[], 120, 0, 'qr', 'MAIN-01', 'published', false, '{"slides":"https://example.com/stairway/step-01-slides.pdf","code":"https://github.com/ieeesbcek/stairway-step-01","recording":"https://www.youtube.com/embed/dQw4w9WgXcQ","reading":[{"label":"Elements of AI (free course)","href":"https://www.elementsofai.com/"}]}'::jsonb, '[]'::jsonb
from public.societies s left join public.tracks t on t.society_id = s.id and t.name = 'AI × Research & Innovation' where s.slug = 'main';
insert into public.event_speakers (event_id, speaker_id, sort_order) select e.id, sp.id, 0 from public.events e, public.speakers sp where e.slug = 'ai-unlocked' and sp.slug = 'anjali-nair';
insert into public.events (society_id, track_id, step_number, slug, title, topic, summary, description, starts_at, ends_at, venue, level, formats, agenda, outcomes, prerequisites, bring, capacity, price_paise, ticket_type, token_prefix, status, is_finale, resources, winners)
select s.id, t.id, 2, 'python-for-ai', 'Python for AI', 'NumPy, Pandas & Data Thinking', 'Arrays, dataframes and the habit of asking good questions of messy data.', 'Every model starts as a spreadsheet nobody wants to clean. This lab gets you fluent in the Python tools AI engineers use daily — NumPy for numbers, Pandas for tables, Matplotlib for seeing — and trains the instinct to spot what''s wrong with a dataset before it bites you.', '2026-09-05T09:30:00+05:30', '2026-09-05T16:30:00+05:30', 'Main Seminar Hall, Block A', 'Beginner', array['Lab']::text[], '[{"time":"09:30","title":"Check-in & coffee","detail":"Grab your badge, find a seat, connect to Wi-Fi."},{"time":"10:00","title":"Data thinking: questions before code"},{"time":"11:30","title":"Short break"},{"time":"11:45","title":"Guided walkthrough","detail":"Live coding with the speaker — follow along on your laptop."},{"time":"13:00","title":"Lunch"},{"time":"14:00","title":"Kerala rainfall dataset deep-dive","detail":"Work in pairs. Mentors float between tables."},{"time":"16:00","title":"Show & tell","detail":"Three teams demo what they built."},{"time":"16:30","title":"Wrap-up & next step preview"}]'::jsonb, array['Manipulate arrays and dataframes confidently','Clean a real-world dataset with missing and messy values','Plot distributions and correlations to find a story','Set up a reusable Colab workflow']::text[], array['Basic Python (variables, loops, functions)']::text[], array['Laptop (8 GB RAM recommended) and charger','Python 3.11+ installed','A Google account for Colab','Curiosity — plenty of it']::text[], 80, 0, 'qr', 'MAIN-02', 'published', false, '{"slides":"https://example.com/stairway/step-02-slides.pdf","notebook":"https://colab.research.google.com/","code":"https://github.com/ieeesbcek/stairway-step-02","recording":"https://www.youtube.com/embed/dQw4w9WgXcQ"}'::jsonb, '[]'::jsonb
from public.societies s left join public.tracks t on t.society_id = s.id and t.name = 'AI × Data Analytics' where s.slug = 'main';
insert into public.event_speakers (event_id, speaker_id, sort_order) select e.id, sp.id, 0 from public.events e, public.speakers sp where e.slug = 'python-for-ai' and sp.slug = 'rahul-varghese';
insert into public.events (society_id, track_id, step_number, slug, title, topic, summary, description, starts_at, ends_at, venue, level, formats, agenda, outcomes, prerequisites, bring, capacity, price_paise, ticket_type, token_prefix, status, is_finale, resources, winners)
select s.id, t.id, 3, 'ml-from-scratch', 'Machine Learning from Scratch', 'Regression to Classification', 'Write gradient descent by hand, then let scikit-learn do it a thousand times faster.', 'No black boxes on this step. You''ll implement linear and logistic regression from first principles, watch the loss curve fall, then graduate to scikit-learn pipelines, cross-validation and the metrics that actually matter when a model goes to production.', '2026-09-19T09:30:00+05:30', '2026-09-19T16:30:00+05:30', 'Main Seminar Hall, Block A', 'Intermediate', array['Workshop']::text[], '[{"time":"09:30","title":"Check-in & coffee","detail":"Grab your badge, find a seat, connect to Wi-Fi."},{"time":"10:00","title":"Learning = minimising a loss"},{"time":"11:30","title":"Short break"},{"time":"11:45","title":"Guided walkthrough","detail":"Live coding with the speaker — follow along on your laptop."},{"time":"13:00","title":"Lunch"},{"time":"14:00","title":"Predict KSRTC bus delays challenge","detail":"Work in pairs. Mentors float between tables."},{"time":"16:00","title":"Show & tell","detail":"Three teams demo what they built."},{"time":"16:30","title":"Wrap-up & next step preview"}]'::jsonb, array['Implement gradient descent in NumPy','Train and evaluate regression and classification models','Choose between accuracy, precision, recall and F1','Avoid data leakage with proper train/test splits']::text[], array['Step 02 or comfortable with NumPy & Pandas','High-school algebra']::text[], array['Laptop (8 GB RAM recommended) and charger','Python 3.11+ installed','A Google account for Colab','Curiosity — plenty of it']::text[], 80, 0, 'qr', 'MAIN-03', 'published', false, '{"slides":"https://example.com/stairway/step-03-slides.pdf","notebook":"https://colab.research.google.com/","code":"https://github.com/ieeesbcek/stairway-step-03","recording":"https://www.youtube.com/embed/dQw4w9WgXcQ"}'::jsonb, '[{"place":"1st","team":"Gradient Gang","project":"Bus delay predictor (MAE 3.2 min)"},{"place":"2nd","team":"Overfit Club","project":"Feature-engineered random forest"}]'::jsonb
from public.societies s left join public.tracks t on t.society_id = s.id and t.name = 'AI × Data Analytics' where s.slug = 'main';
insert into public.event_speakers (event_id, speaker_id, sort_order) select e.id, sp.id, 0 from public.events e, public.speakers sp where e.slug = 'ml-from-scratch' and sp.slug = 'meera-krishnan';
insert into public.events (society_id, track_id, step_number, slug, title, topic, summary, description, starts_at, ends_at, venue, level, formats, agenda, outcomes, prerequisites, bring, capacity, price_paise, ticket_type, token_prefix, status, is_finale, resources, winners)
select s.id, t.id, 1, 'seeing-machines', 'Seeing Machines', 'Computer Vision with OpenCV & CNNs', 'Teach a camera to see: filters, edges, and a CNN that recognises what''s in front of it.', 'Pixels are just numbers — until you know what to do with them. Start with classic OpenCV (filters, edges, contours), then build and train a convolutional neural network that classifies images, and finish by running real-time object detection on your own webcam feed.', '2026-10-10T09:30:00+05:30', '2026-10-10T16:30:00+05:30', 'Main Seminar Hall, Block A', 'Intermediate', array['Lab']::text[], '[{"time":"09:30","title":"Check-in & coffee","detail":"Grab your badge, find a seat, connect to Wi-Fi."},{"time":"10:00","title":"How machines see: from pixels to features"},{"time":"11:30","title":"Short break"},{"time":"11:45","title":"Guided walkthrough","detail":"Live coding with the speaker — follow along on your laptop."},{"time":"13:00","title":"Lunch"},{"time":"14:00","title":"Build a real-time mask/no-mask detector","detail":"Work in pairs. Mentors float between tables."},{"time":"16:00","title":"Show & tell","detail":"Three teams demo what they built."},{"time":"16:30","title":"Wrap-up & next step preview"}]'::jsonb, array['Process images and video streams with OpenCV','Explain convolutions, pooling and feature maps visually','Train a CNN and use transfer learning with a pre-trained model','Run real-time object detection on a webcam']::text[], array['Step 03 or basic ML knowledge','Comfortable with Python']::text[], array['Laptop (8 GB RAM recommended) and charger','Python 3.11+ installed','A Google account for Colab','Curiosity — plenty of it','OpenCV installed (pip install opencv-python)','A working webcam']::text[], 60, 0, 'qr', 'RAS-01', 'published', false, '{}'::jsonb, '[]'::jsonb
from public.societies s left join public.tracks t on t.society_id = s.id and t.name = 'AI × Computer Vision' where s.slug = 'ras';
insert into public.event_speakers (event_id, speaker_id, sort_order) select e.id, sp.id, 0 from public.events e, public.speakers sp where e.slug = 'seeing-machines' and sp.slug = 'arjun-pillai';
insert into public.event_speakers (event_id, speaker_id, sort_order) select e.id, sp.id, 1 from public.events e, public.speakers sp where e.slug = 'seeing-machines' and sp.slug = 'sneha-thomas';
insert into public.events (society_id, track_id, step_number, slug, title, topic, summary, description, starts_at, ends_at, venue, level, formats, agenda, outcomes, prerequisites, bring, capacity, price_paise, ticket_type, token_prefix, status, is_finale, resources, winners)
select s.id, t.id, 4, 'deep-learning-decoded', 'Deep Learning Decoded', 'Neural Networks with PyTorch', 'Tensors, autograd and training loops — build a neural network you actually understand.', 'Open the hood of deep learning. Build a multilayer network neuron by neuron, then rebuild it in PyTorch, learn to read a training curve like a doctor reads an ECG, and fix the classic failure modes: vanishing gradients, overfitting and learning rates gone wild.', '2026-10-24T09:30:00+05:30', '2026-10-24T16:30:00+05:30', 'Main Seminar Hall, Block A', 'Intermediate', array['Workshop']::text[], '[{"time":"09:30","title":"Check-in & coffee","detail":"Grab your badge, find a seat, connect to Wi-Fi."},{"time":"10:00","title":"Neurons, layers and the chain rule"},{"time":"11:30","title":"Short break"},{"time":"11:45","title":"Guided walkthrough","detail":"Live coding with the speaker — follow along on your laptop."},{"time":"13:00","title":"Lunch"},{"time":"14:00","title":"Handwritten Malayalam digit recogniser","detail":"Work in pairs. Mentors float between tables."},{"time":"16:00","title":"Show & tell","detail":"Three teams demo what they built."},{"time":"16:30","title":"Wrap-up & next step preview"}]'::jsonb, array['Write a PyTorch training loop from memory','Diagnose overfitting and underfitting from loss curves','Use regularisation, dropout and batch norm effectively','Train on a GPU in Colab']::text[], array['Step 03 or equivalent ML basics']::text[], array['Laptop (8 GB RAM recommended) and charger','Python 3.11+ installed','A Google account for Colab','Curiosity — plenty of it','PyTorch installed or Colab ready']::text[], 60, 0, 'qr', 'MAIN-04', 'published', false, '{}'::jsonb, '[]'::jsonb
from public.societies s left join public.tracks t on t.society_id = s.id and t.name = 'AI × Research & Innovation' where s.slug = 'main';
insert into public.event_speakers (event_id, speaker_id, sort_order) select e.id, sp.id, 0 from public.events e, public.speakers sp where e.slug = 'deep-learning-decoded' and sp.slug = 'vishnu-prasad';
insert into public.events (society_id, track_id, step_number, slug, title, topic, summary, description, starts_at, ends_at, venue, level, formats, agenda, outcomes, prerequisites, bring, capacity, price_paise, ticket_type, token_prefix, status, is_finale, resources, winners)
select s.id, t.id, 1, 'language-and-machines', 'Language & Machines', 'NLP and Transformers', 'From word counts to attention: how machines learned to read.', 'Trace the path from bag-of-words to embeddings to the transformer. You''ll visualise attention, fine-tune a small transformer for sentiment analysis on Malayalam–English code-mixed text, and understand why ''Attention Is All You Need'' changed everything.', '2026-11-07T09:30:00+05:30', '2026-11-07T16:30:00+05:30', 'Main Seminar Hall, Block A', 'Intermediate', array['Workshop']::text[], '[{"time":"09:30","title":"Check-in & coffee","detail":"Grab your badge, find a seat, connect to Wi-Fi."},{"time":"10:00","title":"From words to vectors to attention"},{"time":"11:30","title":"Short break"},{"time":"11:45","title":"Guided walkthrough","detail":"Live coding with the speaker — follow along on your laptop."},{"time":"13:00","title":"Lunch"},{"time":"14:00","title":"Code-mixed sentiment fine-tuning sprint","detail":"Work in pairs. Mentors float between tables."},{"time":"16:00","title":"Show & tell","detail":"Three teams demo what they built."},{"time":"16:30","title":"Wrap-up & next step preview"}]'::jsonb, array['Tokenise text and build word embeddings','Explain self-attention with a whiteboard sketch','Fine-tune a Hugging Face transformer','Evaluate an NLP model honestly']::text[], array['Step 05 recommended','PyTorch basics']::text[], array['Laptop (8 GB RAM recommended) and charger','Python 3.11+ installed','A Google account for Colab','Curiosity — plenty of it']::text[], 60, 0, 'qr', 'CS-01', 'published', false, '{}'::jsonb, '[]'::jsonb
from public.societies s left join public.tracks t on t.society_id = s.id and t.name = 'AI × Software Engineering' where s.slug = 'cs';
insert into public.event_speakers (event_id, speaker_id, sort_order) select e.id, sp.id, 0 from public.events e, public.speakers sp where e.slug = 'language-and-machines' and sp.slug = 'anjali-nair';
insert into public.events (society_id, track_id, step_number, slug, title, topic, summary, description, starts_at, ends_at, venue, level, formats, agenda, outcomes, prerequisites, bring, capacity, price_paise, ticket_type, token_prefix, status, is_finale, resources, winners)
select s.id, t.id, 5, 'inside-llms', 'Inside LLMs', 'How ChatGPT-like Models Work', 'Pre-training, fine-tuning, RLHF and inference — the full life of a large language model.', 'What actually happens between your prompt and the reply? We follow a large language model from raw web text to a helpful assistant: tokenisers, pre-training, instruction tuning, preference optimisation, and the tricks that make inference fast. In the lab you''ll train a tiny GPT on Malayalam poetry.', '2026-11-21T09:30:00+05:30', '2026-11-21T16:30:00+05:30', 'Main Seminar Hall, Block A', 'Advanced', array['Talk','Lab']::text[], '[{"time":"09:30","title":"Check-in & coffee","detail":"Grab your badge, find a seat, connect to Wi-Fi."},{"time":"10:00","title":"The life of a large language model"},{"time":"11:30","title":"Short break"},{"time":"11:45","title":"Guided walkthrough","detail":"Live coding with the speaker — follow along on your laptop."},{"time":"13:00","title":"Lunch"},{"time":"14:00","title":"nanoGPT on Malayalam poetry","detail":"Work in pairs. Mentors float between tables."},{"time":"16:00","title":"Show & tell","detail":"Three teams demo what they built."},{"time":"16:30","title":"Wrap-up & next step preview"}]'::jsonb, array['Describe the LLM training pipeline end to end','Explain context windows, temperature and sampling','Train a character-level GPT from scratch','Reason about cost, latency and model size trade-offs']::text[], array['Step 06 or transformer basics']::text[], array['Laptop (8 GB RAM recommended) and charger','Python 3.11+ installed','A Google account for Colab','Curiosity — plenty of it','Colab with GPU runtime enabled']::text[], 60, 0, 'qr', 'MAIN-05', 'published', false, '{}'::jsonb, '[]'::jsonb
from public.societies s left join public.tracks t on t.society_id = s.id and t.name = 'AI × Generative Media' where s.slug = 'main';
insert into public.event_speakers (event_id, speaker_id, sort_order) select e.id, sp.id, 0 from public.events e, public.speakers sp where e.slug = 'inside-llms' and sp.slug = 'dr-joseph-mathew';
insert into public.event_speakers (event_id, speaker_id, sort_order) select e.id, sp.id, 1 from public.events e, public.speakers sp where e.slug = 'inside-llms' and sp.slug = 'vishnu-prasad';
insert into public.events (society_id, track_id, step_number, slug, title, topic, summary, description, starts_at, ends_at, venue, level, formats, agenda, outcomes, prerequisites, bring, capacity, price_paise, ticket_type, token_prefix, status, is_finale, resources, winners)
select s.id, t.id, 2, 'prompt-engineering-agents', 'Prompt Engineering & AI Agents', 'Tools, memory and autonomous workflows', 'Turn a chatbot into a teammate: prompting patterns, tool use and agent loops.', 'Prompting is a skill, and agents are where it pays off. Learn structured prompting patterns, give a model tools to call, add retrieval so it knows your documents, and wire it all into an agent that completes a multi-step task — then learn how to evaluate it so it doesn''t quietly fail.', '2026-12-05T09:30:00+05:30', '2026-12-05T16:30:00+05:30', 'Main Seminar Hall, Block A', 'Intermediate', array['Hands-on']::text[], '[{"time":"09:30","title":"Check-in & coffee","detail":"Grab your badge, find a seat, connect to Wi-Fi."},{"time":"10:00","title":"Patterns that make prompts reliable"},{"time":"11:30","title":"Short break"},{"time":"11:45","title":"Guided walkthrough","detail":"Live coding with the speaker — follow along on your laptop."},{"time":"13:00","title":"Lunch"},{"time":"14:00","title":"Build a campus-help agent for CEK","detail":"Work in pairs. Mentors float between tables."},{"time":"16:00","title":"Show & tell","detail":"Three teams demo what they built."},{"time":"16:30","title":"Wrap-up & next step preview"}]'::jsonb, array['Write reliable prompts with examples and structure','Build a retrieval-augmented (RAG) assistant','Give an LLM tools and let it act','Evaluate and guard an agent''s outputs']::text[], array['Python basics','Any prior step helps']::text[], array['Laptop (8 GB RAM recommended) and charger','Python 3.11+ installed','A Google account for Colab','Curiosity — plenty of it','Free API key from your LLM provider of choice']::text[], 70, 0, 'qr', 'CS-02', 'published', false, '{}'::jsonb, '[]'::jsonb
from public.societies s left join public.tracks t on t.society_id = s.id and t.name = 'AI × Web Development' where s.slug = 'cs';
insert into public.event_speakers (event_id, speaker_id, sort_order) select e.id, sp.id, 0 from public.events e, public.speakers sp where e.slug = 'prompt-engineering-agents' and sp.slug = 'nikhil-raj';
insert into public.events (society_id, track_id, step_number, slug, title, topic, summary, description, starts_at, ends_at, venue, level, formats, agenda, outcomes, prerequisites, bring, capacity, price_paise, ticket_type, token_prefix, status, is_finale, resources, winners)
select s.id, t.id, 6, 'generative-ai', 'Generative AI', 'Images, Audio & Creativity', 'Diffusion models, voice synthesis and the craft of making machines create.', 'Explore how diffusion models paint, how neural audio models speak and sing, and how artists are using both. You''ll run Stable Diffusion locally, fine-tune it on a small style dataset, and compose a short multimedia piece — plus a frank discussion of copyright and consent.', '2027-01-09T09:30:00+05:30', '2027-01-09T16:30:00+05:30', 'Main Seminar Hall, Block A', 'Intermediate', array['Lab']::text[], '[{"time":"09:30","title":"Check-in & coffee","detail":"Grab your badge, find a seat, connect to Wi-Fi."},{"time":"10:00","title":"Noise to art: diffusion explained"},{"time":"11:30","title":"Short break"},{"time":"11:45","title":"Guided walkthrough","detail":"Live coding with the speaker — follow along on your laptop."},{"time":"13:00","title":"Lunch"},{"time":"14:00","title":"Kerala mural style LoRA challenge","detail":"Work in pairs. Mentors float between tables."},{"time":"16:00","title":"Show & tell","detail":"Three teams demo what they built."},{"time":"16:30","title":"Wrap-up & next step preview"}]'::jsonb, array['Explain how diffusion turns noise into images','Generate and control images with prompts and ControlNet','Fine-tune a small LoRA on a custom style','Discuss the ethics of generative media']::text[], array['Step 05 recommended']::text[], array['Laptop (8 GB RAM recommended) and charger','Python 3.11+ installed','A Google account for Colab','Curiosity — plenty of it','Headphones']::text[], 60, 0, 'qr', 'MAIN-06', 'published', false, '{}'::jsonb, '[]'::jsonb
from public.societies s left join public.tracks t on t.society_id = s.id and t.name = 'AI × Generative Media' where s.slug = 'main';
insert into public.event_speakers (event_id, speaker_id, sort_order) select e.id, sp.id, 0 from public.events e, public.speakers sp where e.slug = 'generative-ai' and sp.slug = 'sneha-thomas';
insert into public.events (society_id, track_id, step_number, slug, title, topic, summary, description, starts_at, ends_at, venue, level, formats, agenda, outcomes, prerequisites, bring, capacity, price_paise, ticket_type, token_prefix, status, is_finale, resources, winners)
select s.id, t.id, 1, 'ai-on-the-edge', 'AI on the Edge', 'AI with Microcontrollers & IoT', 'Shrink a model until it fits on a ₹500 board — and make it listen, see and react.', 'AI doesn''t only live in data centres. In this hardware lab you''ll quantise a model with TensorFlow Lite Micro, deploy keyword spotting to an ESP32, and build a sensor-driven device that makes decisions without the cloud. Kits are provided; you keep what you build.', '2027-01-23T09:30:00+05:30', '2027-01-23T16:30:00+05:30', 'Main Seminar Hall, Block A', 'Advanced', array['Lab']::text[], '[{"time":"09:30","title":"Check-in & coffee","detail":"Grab your badge, find a seat, connect to Wi-Fi."},{"time":"10:00","title":"Tiny models, big impact"},{"time":"11:30","title":"Short break"},{"time":"11:45","title":"Guided walkthrough","detail":"Live coding with the speaker — follow along on your laptop."},{"time":"13:00","title":"Lunch"},{"time":"14:00","title":"Build a keyword-spotting smart switch","detail":"Work in pairs. Mentors float between tables."},{"time":"16:00","title":"Show & tell","detail":"Three teams demo what they built."},{"time":"16:30","title":"Wrap-up & next step preview"}]'::jsonb, array['Quantise and compress a neural network','Deploy a model to an ESP32 microcontroller','Build a voice- or sensor-triggered edge device','Measure latency, memory and power']::text[], array['Step 05','Basic electronics or Arduino exposure helps']::text[], array['Laptop (8 GB RAM recommended) and charger','Python 3.11+ installed','A Google account for Colab','Curiosity — plenty of it','Arduino IDE installed','USB-C / micro-USB cable']::text[], 40, 0, 'qr', 'IAS-01', 'published', false, '{}'::jsonb, '[]'::jsonb
from public.societies s left join public.tracks t on t.society_id = s.id and t.name = 'AI × Industrial Automation' where s.slug = 'ias';
insert into public.event_speakers (event_id, speaker_id, sort_order) select e.id, sp.id, 0 from public.events e, public.speakers sp where e.slug = 'ai-on-the-edge' and sp.slug = 'arjun-pillai';
insert into public.events (society_id, track_id, step_number, slug, title, topic, summary, description, starts_at, ends_at, venue, level, formats, agenda, outcomes, prerequisites, bring, capacity, price_paise, ticket_type, token_prefix, status, is_finale, resources, winners)
select s.id, t.id, 7, 'responsible-ai', 'Responsible AI', 'Ethics, Bias & Safety', 'Who gets hurt when models go wrong — and how builders can do better.', 'A panel of researchers, an industry practitioner and a lawyer take on the hard questions: bias in datasets, explainability, deepfakes, safety evaluations and India''s evolving AI policy. Bring your questions — half the session is open floor.', '2027-02-06T10:00:00+05:30', '2027-02-06T15:30:00+05:30', 'Main Seminar Hall, Block A', 'All levels', array['Panel']::text[], '[{"time":"10:00","title":"Opening provocation"},{"time":"10:30","title":"Panel: Who is AI built for?"},{"time":"12:00","title":"Case-study breakouts"},{"time":"13:00","title":"Lunch"},{"time":"14:00","title":"Open floor Q&A"},{"time":"15:00","title":"Summit briefing for Step 12"}]'::jsonb, array['Spot common sources of bias in data and models','Apply a lightweight fairness checklist to your project','Understand the basics of AI safety evaluation','Discuss AI regulation in India and worldwide']::text[], array['None']::text[], array['Your questions','An open mind']::text[], 150, 0, 'qr', 'MAIN-07', 'published', false, '{}'::jsonb, '[]'::jsonb
from public.societies s left join public.tracks t on t.society_id = s.id and t.name = 'AI × Cybersecurity' where s.slug = 'main';
insert into public.event_speakers (event_id, speaker_id, sort_order) select e.id, sp.id, 0 from public.events e, public.speakers sp where e.slug = 'responsible-ai' and sp.slug = 'dr-joseph-mathew';
insert into public.event_speakers (event_id, speaker_id, sort_order) select e.id, sp.id, 1 from public.events e, public.speakers sp where e.slug = 'responsible-ai' and sp.slug = 'meera-krishnan';
insert into public.event_speakers (event_id, speaker_id, sort_order) select e.id, sp.id, 2 from public.events e, public.speakers sp where e.slug = 'responsible-ai' and sp.slug = 'nikhil-raj';
insert into public.events (society_id, track_id, step_number, slug, title, topic, summary, description, starts_at, ends_at, venue, level, formats, agenda, outcomes, prerequisites, bring, capacity, price_paise, ticket_type, token_prefix, status, is_finale, resources, winners)
select s.id, t.id, 8, 'the-summit', 'THE SUMMIT', 'st(AI)rway 24-Hour AI Hackathon', '24 hours, one problem statement, every step you''ve climbed. Build something that matters.', 'The top of the stairway. Teams of 2–4 get 24 hours to build an AI solution for a real problem from Kerala''s healthcare, agriculture, transport or education sectors. Mentors on call all night, food that doesn''t stop, and a ₹1,00,000 prize pool for the teams that climb highest.', '2027-02-27T10:00:00+05:30', '2027-02-28T10:00:00+05:30', 'Main Seminar Hall, Block A', 'All levels', array['Hackathon','Competition']::text[], '[{"time":"Sat 10:00","title":"Opening ceremony & problem statements"},{"time":"Sat 11:00","title":"Hacking begins"},{"time":"Sat 18:00","title":"Mentor round 1"},{"time":"Sun 00:00","title":"Midnight check-in & surprise challenge"},{"time":"Sun 06:00","title":"Mentor round 2"},{"time":"Sun 10:00","title":"Code freeze, demos & judging"}]'::jsonb, array['Ship a working AI prototype in 24 hours','Pitch to a jury of industry and academic judges','Work in a team under real constraints','Earn the Summit Climber badge']::text[], array['Teams of 2–4','At least one prior step recommended']::text[], array['Laptop (8 GB RAM recommended) and charger','Python 3.11+ installed','A Google account for Colab','Curiosity — plenty of it','Extension board','Sleeping bag (optional, brave)','Your team']::text[], 200, 0, 'qr', 'MAIN-08', 'published', true, '{}'::jsonb, '[]'::jsonb
from public.societies s left join public.tracks t on t.society_id = s.id and t.name = 'AI × Research & Innovation' where s.slug = 'main';
insert into public.event_speakers (event_id, speaker_id, sort_order) select e.id, sp.id, 0 from public.events e, public.speakers sp where e.slug = 'the-summit' and sp.slug = 'dr-joseph-mathew';
insert into public.event_speakers (event_id, speaker_id, sort_order) select e.id, sp.id, 1 from public.events e, public.speakers sp where e.slug = 'the-summit' and sp.slug = 'anjali-nair';
insert into public.event_speakers (event_id, speaker_id, sort_order) select e.id, sp.id, 2 from public.events e, public.speakers sp where e.slug = 'the-summit' and sp.slug = 'nikhil-raj';
insert into public.event_speakers (event_id, speaker_id, sort_order) select e.id, sp.id, 3 from public.events e, public.speakers sp where e.slug = 'the-summit' and sp.slug = 'vishnu-prasad';
insert into public.events (society_id, track_id, step_number, slug, title, topic, summary, description, starts_at, ends_at, venue, level, formats, agenda, outcomes, prerequisites, bring, capacity, price_paise, ticket_type, token_prefix, status, is_finale, resources, winners)
select s.id, t.id, 1, 'wie-ai-healthtech', 'Code Her Way: AI in HealthTech', 'Medical data, diagnosis models and ethics', 'Build a small diagnostic model on open health data and learn where AI helps — and where it must not decide alone.', 'Start with how hospitals actually use AI today, then train a simple classifier on an open medical dataset and examine its mistakes. We close with the questions every health-AI builder must answer: consent, bias and accountability.', '2026-10-17T09:30:00+05:30', '2026-10-17T16:30:00+05:30', 'Main Seminar Hall, Block A', 'Beginner', array['Workshop']::text[], '[{"time":"09:30","title":"Check-in & coffee"},{"time":"10:00","title":"Talk: AI in Indian healthcare today"},{"time":"11:45","title":"Guided walkthrough"},{"time":"13:00","title":"Lunch"},{"time":"14:00","title":"Diagnose-with-data lab","detail":"Work in pairs. Mentors float between tables."},{"time":"16:00","title":"Show & tell and wrap-up"}]'::jsonb, array['Explain common uses of AI in healthcare','Train and evaluate a simple diagnostic classifier','Spot bias in a medical dataset','Apply a responsible-AI checklist to a health project']::text[], array['None — beginners welcome']::text[], array['Laptop and charger','A Google account for Colab']::text[], 60, 0, 'qr', 'WIE-01', 'published', false, '{}'::jsonb, '[]'::jsonb
from public.societies s left join public.tracks t on t.society_id = s.id and t.name = 'AI × HealthTech' where s.slug = 'wie';
insert into public.event_speakers (event_id, speaker_id, sort_order) select e.id, sp.id, 0 from public.events e, public.speakers sp where e.slug = 'wie-ai-healthtech' and sp.slug = 'meera-krishnan';
insert into public.events (society_id, track_id, step_number, slug, title, topic, summary, description, starts_at, ends_at, venue, level, formats, agenda, outcomes, prerequisites, bring, capacity, price_paise, ticket_type, token_prefix, status, is_finale, resources, winners)
select s.id, t.id, 2, 'wie-designing-ai-for-everyone', 'Designing AI for Everyone', 'Accessible, inclusive AI products', 'Make AI products that work for people the tutorials forget — accessibility, language and context.', 'Explore how voice assistants, captioning and recommendation systems fail different users, then redesign an AI feature with accessibility and local-language users in mind. Hands-on with speech and vision APIs.', '2026-10-31T09:30:00+05:30', '2026-10-31T16:30:00+05:30', 'Main Seminar Hall, Block A', 'Beginner', array['Workshop']::text[], '[{"time":"09:30","title":"Check-in & coffee"},{"time":"10:00","title":"Talk: Who does AI leave out?"},{"time":"11:45","title":"Guided walkthrough"},{"time":"13:00","title":"Lunch"},{"time":"14:00","title":"Redesign-an-AI-feature sprint","detail":"Work in pairs. Mentors float between tables."},{"time":"16:00","title":"Show & tell and wrap-up"}]'::jsonb, array['Audit an AI feature for accessibility gaps','Prototype an inclusive AI interaction','Use speech and vision APIs in a small demo']::text[], array['None']::text[], array['Laptop and charger']::text[], 60, 0, 'qr', 'WIE-02', 'published', false, '{}'::jsonb, '[]'::jsonb
from public.societies s left join public.tracks t on t.society_id = s.id and t.name = 'AI × Inclusive Design' where s.slug = 'wie';
insert into public.event_speakers (event_id, speaker_id, sort_order) select e.id, sp.id, 0 from public.events e, public.speakers sp where e.slug = 'wie-designing-ai-for-everyone' and sp.slug = 'sneha-thomas';
insert into public.events (society_id, track_id, step_number, slug, title, topic, summary, description, starts_at, ends_at, venue, level, formats, agenda, outcomes, prerequisites, bring, capacity, price_paise, ticket_type, token_prefix, status, is_finale, resources, winners)
select s.id, t.id, 3, 'wie-ai-for-good', 'AI for Good: Social Impact Sprint', 'Solving local problems with AI', 'A one-day build sprint on real problems from Kottayam — water, transport, safety and education.', 'Teams of two to four pick a local problem statement, find data, and prototype an AI-assisted solution in a day. Mentors help scope; a jury picks three teams to present at the next WIE session.', '2026-11-14T09:30:00+05:30', '2026-11-14T17:00:00+05:30', 'Main Seminar Hall, Block A', 'Intermediate', array['Competition']::text[], '[{"time":"09:30","title":"Problem statements & team formation"},{"time":"10:30","title":"Build sprint begins"},{"time":"13:00","title":"Lunch + mentor round"},{"time":"15:30","title":"Demos"},{"time":"16:30","title":"Jury results"}]'::jsonb, array['Scope a social-impact problem for AI','Prototype a working demo in a day','Pitch the impact and limits of your solution']::text[], array['Basic Python','Teams of 2–4 (solo sign-ups get matched)']::text[], array['Laptop and charger','Your team']::text[], 80, 0, 'qr', 'WIE-03', 'published', false, '{}'::jsonb, '[]'::jsonb
from public.societies s left join public.tracks t on t.society_id = s.id and t.name = 'AI × Social Impact' where s.slug = 'wie';
insert into public.event_speakers (event_id, speaker_id, sort_order) select e.id, sp.id, 0 from public.events e, public.speakers sp where e.slug = 'wie-ai-for-good' and sp.slug = 'anjali-nair';
insert into public.events (society_id, track_id, step_number, slug, title, topic, summary, description, starts_at, ends_at, venue, level, formats, agenda, outcomes, prerequisites, bring, capacity, price_paise, ticket_type, token_prefix, status, is_finale, resources, winners)
select s.id, t.id, 4, 'wie-lead-with-ai', 'Lead with AI: Founders & Leaders Panel', 'Careers, startups and leadership in AI', 'Women founders and engineering leaders on building careers and companies in AI.', 'An afternoon of honest conversations: getting your first AI role, starting up from Kerala, leading technical teams and negotiating your worth. Speed-mentoring tables close the day.', '2026-11-28T10:00:00+05:30', '2026-11-28T15:00:00+05:30', 'Main Seminar Hall, Block A', 'All levels', array['Panel','Talk']::text[], '[{"time":"10:00","title":"Opening keynote"},{"time":"10:45","title":"Panel: Building a career in AI"},{"time":"12:15","title":"Lunch"},{"time":"13:15","title":"Speed-mentoring tables"},{"time":"14:30","title":"Closing & next steps"}]'::jsonb, array['Map career paths into AI','Learn how founders validate AI startup ideas','Get one-to-one advice at mentoring tables']::text[], array['None']::text[], array['Questions','Your CV if you want feedback']::text[], 120, 0, 'qr', 'WIE-04', 'published', false, '{}'::jsonb, '[]'::jsonb
from public.societies s left join public.tracks t on t.society_id = s.id and t.name = 'AI × Entrepreneurship & Leadership' where s.slug = 'wie';
insert into public.event_speakers (event_id, speaker_id, sort_order) select e.id, sp.id, 0 from public.events e, public.speakers sp where e.slug = 'wie-lead-with-ai' and sp.slug = 'anjali-nair';
insert into public.event_speakers (event_id, speaker_id, sort_order) select e.id, sp.id, 1 from public.events e, public.speakers sp where e.slug = 'wie-lead-with-ai' and sp.slug = 'meera-krishnan';
insert into public.event_speakers (event_id, speaker_id, sort_order) select e.id, sp.id, 2 from public.events e, public.speakers sp where e.slug = 'wie-lead-with-ai' and sp.slug = 'sneha-thomas';
insert into public.sponsors (name, url, logo_url, tier, tier_size, sort_order) values ('Nimbus Labs', 'https://example.com', null, 'Title Sponsor', 'xl', 0);
insert into public.sponsors (name, url, logo_url, tier, tier_size, sort_order) values ('Monsoon AI', 'https://example.com', null, 'Gold', 'lg', 1);
insert into public.sponsors (name, url, logo_url, tier, tier_size, sort_order) values ('Edgeworks Robotics', 'https://example.com', null, 'Gold', 'lg', 2);
insert into public.sponsors (name, url, logo_url, tier, tier_size, sort_order) values ('Backwater Analytics', 'https://example.com', null, 'Silver', 'md', 3);
insert into public.sponsors (name, url, logo_url, tier, tier_size, sort_order) values ('AgentForge', 'https://example.com', null, 'Silver', 'md', 4);
insert into public.sponsors (name, url, logo_url, tier, tier_size, sort_order) values ('Kottayam Cloud', 'https://example.com', null, 'Silver', 'md', 5);
insert into public.sponsors (name, url, logo_url, tier, tier_size, sort_order) values ('IEEE Kerala Section', 'https://ieeekerala.org', null, 'Community Partners', 'sm', 6);
insert into public.sponsors (name, url, logo_url, tier, tier_size, sort_order) values ('TinkerHub CEK', 'https://example.com', null, 'Community Partners', 'sm', 7);
insert into public.sponsors (name, url, logo_url, tier, tier_size, sort_order) values ('GDG Kottayam', 'https://example.com', null, 'Community Partners', 'sm', 8);
insert into public.sponsors (name, url, logo_url, tier, tier_size, sort_order) values ('Kerala AI Collective', 'https://example.com', null, 'Community Partners', 'sm', 9);
insert into public.sponsors (name, url, logo_url, tier, tier_size, sort_order) values ('Campus Pulse', 'https://example.com', null, 'Media Partners', 'sm', 10);
insert into public.sponsors (name, url, logo_url, tier, tier_size, sort_order) values ('TechKerala Weekly', 'https://example.com', null, 'Media Partners', 'sm', 11);
insert into public.team_members (name, role, "group", photo_url, fun_fact, links, sort_order) values ('Dr. Lekshmi S.', 'Branch Counselor', 'Leadership', null, 'Has graded 4,000+ lab records and still enjoys it.', '{"linkedin":"https://linkedin.com"}'::jsonb, 0);
insert into public.team_members (name, role, "group", photo_url, fun_fact, links, sort_order) values ('Aaron Jacob', 'Chair', 'Leadership', null, 'Debugs code by explaining it to his cat, Tensor.', '{"linkedin":"https://linkedin.com","instagram":"https://instagram.com"}'::jsonb, 1);
insert into public.team_members (name, role, "group", photo_url, fun_fact, links, sort_order) values ('Devika Suresh', 'Vice Chair', 'Leadership', null, 'Can solve a Rubik''s cube in under a minute — blindfolded attempts pending.', '{"linkedin":"https://linkedin.com"}'::jsonb, 2);
insert into public.team_members (name, role, "group", photo_url, fun_fact, links, sort_order) values ('Harikrishnan P.', 'Secretary', 'Leadership', null, 'Keeps a spreadsheet of his spreadsheets.', '{"linkedin":"https://linkedin.com"}'::jsonb, 3);
insert into public.team_members (name, role, "group", photo_url, fun_fact, links, sort_order) values ('Nandana Rajeev', 'Treasurer', 'Leadership', null, 'Tracks every rupee — and every cup of chai.', '{"linkedin":"https://linkedin.com"}'::jsonb, 4);
insert into public.team_members (name, role, "group", photo_url, fun_fact, links, sort_order) values ('Aditya Menon', 'Event Coordinator', 'Coordinators', null, 'Has walked every staircase on campus. Counted the steps too.', '{"linkedin":"https://linkedin.com","instagram":"https://instagram.com"}'::jsonb, 5);
insert into public.team_members (name, role, "group", photo_url, fun_fact, links, sort_order) values ('Fathima Rasheed', 'Event Coordinator', 'Coordinators', null, 'Plans events like heists. Nothing ever goes off-script.', '{"linkedin":"https://linkedin.com"}'::jsonb, 6);
insert into public.team_members (name, role, "group", photo_url, fun_fact, links, sort_order) values ('Sidharth Unni', 'Tech Lead', 'Tech', null, 'Wrote this site''s neural field at 2 a.m. on instant noodles.', '{"github":"https://github.com","linkedin":"https://linkedin.com"}'::jsonb, 7);
insert into public.team_members (name, role, "group", photo_url, fun_fact, links, sort_order) values ('Gayathri Mohan', 'Web Developer', 'Tech', null, 'Refuses to ship anything without a dark mode.', '{"github":"https://github.com"}'::jsonb, 8);
insert into public.team_members (name, role, "group", photo_url, fun_fact, links, sort_order) values ('Joel Thomas', 'Design Lead', 'Design', null, 'Has opinions about kerning. Many opinions.', '{"instagram":"https://instagram.com","linkedin":"https://linkedin.com"}'::jsonb, 9);
insert into public.team_members (name, role, "group", photo_url, fun_fact, links, sort_order) values ('Ann Maria Joseph', 'Visual Designer', 'Design', null, 'Designed the (AI) glyph on a bus ride home.', '{"instagram":"https://instagram.com"}'::jsonb, 10);
insert into public.team_members (name, role, "group", photo_url, fun_fact, links, sort_order) values ('Rohan George', 'Media Lead', 'Media', null, 'Shoots every event on a phone older than the freshers.', '{"instagram":"https://instagram.com","linkedin":"https://linkedin.com"}'::jsonb, 11);
insert into public.faqs (question, answer, sort_order) values ('Who can participate?', 'Any student — any branch, any year, any college. Faculty and alumni are welcome too. If you''re curious about AI, you belong on the stairway.', 0);
insert into public.faqs (question, answer, sort_order) values ('Is st(AI)rway free? Is there a registration fee?', 'Most weekends are free for IEEE members and carry a small ₹100 fee for non-members to cover lunch and materials. The Summit hackathon has a ₹200 team fee. Fees are listed on each weekend''s page.', 1);
insert into public.faqs (question, answer, sort_order) values ('Do I need prior AI or coding knowledge?', 'Not for the early steps. Steps 01 and 02 assume nothing beyond basic Python curiosity. Later steps list their prerequisites clearly so you can decide where to jump in.', 2);
insert into public.faqs (question, answer, sort_order) values ('Can students from other colleges join?', 'Absolutely. Register like everyone else and bring your college ID on the day.', 3);
insert into public.faqs (question, answer, sort_order) values ('Do I need to be an IEEE member? Are there benefits for members?', 'No membership required. Members get free entry to most weekends, priority seats when a step is full, and IEEE-verified certificates.', 4);
insert into public.faqs (question, answer, sort_order) values ('Do I need to attend every weekend?', 'No — each step stands on its own. But attending consecutive weekends earns streak badges, and the climb is more fun when you keep going.', 5);
insert into public.faqs (question, answer, sort_order) values ('What should I bring?', 'A laptop with charger, Python installed, and a Google account for Colab. Each weekend page lists any extra software or hardware.', 6);
insert into public.faqs (question, answer, sort_order) values ('Will I get a certificate?', 'Yes. Every step you attend earns a participation certificate from IEEE SB CEK. Winners and Summit finishers receive merit certificates.', 7);
insert into public.faqs (question, answer, sort_order) values ('Will sessions be recorded?', 'Talks are recorded and posted to the Resources hub within a week. Hands-on labs are best experienced live.', 8);
insert into public.faqs (question, answer, sort_order) values ('Are sessions online, offline, or hybrid?', 'Offline first, at the College of Engineering Kidangoor. Selected talks are live-streamed on our YouTube channel.', 9);
insert into public.faqs (question, answer, sort_order) values ('How do I join the community group?', 'Hit the WhatsApp button in the community section below. It''s where we post announcements, resources and memes.', 10);
insert into public.faqs (question, answer, sort_order) values ('How can I become a speaker, volunteer, or sponsor?', 'Speakers can apply through the speaker card in the Speakers section, volunteers through the community section, and sponsors can download our deck or email the sponsorship team.', 11);
insert into public.testimonials (quote, name, detail, step_label, photo_url, sort_order) values ('I walked in not knowing what a tensor was. By lunch I had trained my first model. By evening I''d signed up for every remaining step.', 'Akhil Sabu', 'S3 · Electronics', 'Step 01 — AI Unlocked', null, 0);
insert into public.testimonials (quote, name, detail, step_label, photo_url, sort_order) values ('The Pandas lab was the first time data cleaning felt like solving a mystery instead of a chore.', 'Riya Benny', 'S5 · Computer Science', 'Step 02 — Python for AI', null, 1);
insert into public.testimonials (quote, name, detail, step_label, photo_url, sort_order) values ('Writing gradient descent by hand finally made the maths click. Our team won the bus-delay challenge!', 'Sreehari K.', 'S7 · Computer Science', 'Step 03 — ML from Scratch', null, 2);
insert into public.testimonials (quote, name, detail, step_label, photo_url, sort_order) values ('Mentors actually sat with us and debugged. It felt less like an event and more like a lab with friends.', 'Neha Philip', 'S5 · Electrical', 'Step 03 — ML from Scratch', null, 3);
insert into public.testimonials (quote, name, detail, step_label, photo_url, sort_order) values ('I came from a mechanical background and nobody made me feel out of place. The stairway really does start at the bottom.', 'Arun Das', 'S3 · Mechanical', 'Step 01 — AI Unlocked', null, 4);
insert into public.testimonials (quote, name, detail, step_label, photo_url, sort_order) values ('Professional, well-paced and genuinely fun. I''ve been to paid bootcamps that were less organised.', 'Merin Jose', 'Alumna · 2024', 'Step 02 — Python for AI', null, 5);
insert into public.gallery_items (event_id, society_id, image_url, caption, alt, ratio, sort_order) select e.id, e.society_id, null, 'A packed seminar hall for the very first step', 'Audience in a seminar hall during the opening keynote', 'wide', 0 from public.events e where e.slug = 'ai-unlocked';
insert into public.gallery_items (event_id, society_id, image_url, caption, alt, ratio, sort_order) select e.id, e.society_id, null, 'First models trained before lunch', 'Students gathered around a laptop training a model', 'tall', 1 from public.events e where e.slug = 'ai-unlocked';
insert into public.gallery_items (event_id, society_id, image_url, caption, alt, ratio, sort_order) select e.id, e.society_id, null, 'Mapping the stairway on the whiteboard', 'Whiteboard covered in a hand-drawn AI roadmap', 'square', 2 from public.events e where e.slug = 'ai-unlocked';
insert into public.gallery_items (event_id, society_id, image_url, caption, alt, ratio, sort_order) select e.id, e.society_id, null, 'Pandas, chai and messy rainfall data', 'Students coding in pairs in a computer lab', 'square', 3 from public.events e where e.slug = 'python-for-ai';
insert into public.gallery_items (event_id, society_id, image_url, caption, alt, ratio, sort_order) select e.id, e.society_id, null, 'Mentors debugging side by side', 'A mentor helping a student debug code', 'tall', 4 from public.events e where e.slug = 'python-for-ai';
insert into public.gallery_items (event_id, society_id, image_url, caption, alt, ratio, sort_order) select e.id, e.society_id, null, 'Gradient descent, by hand, on glass', 'Speaker drawing a loss curve on a glass board', 'wide', 5 from public.events e where e.slug = 'ml-from-scratch';
insert into public.gallery_items (event_id, society_id, image_url, caption, alt, ratio, sort_order) select e.id, e.society_id, null, 'Gradient Gang takes the bus-delay challenge', 'Winning team holding certificates on stage', 'square', 6 from public.events e where e.slug = 'ml-from-scratch';
insert into public.gallery_items (event_id, society_id, image_url, caption, alt, ratio, sort_order) select e.id, e.society_id, null, 'Show & tell: three teams, three approaches', 'Student presenting results on a projector', 'tall', 7 from public.events e where e.slug = 'ml-from-scratch';
commit;
